parser: babel-eslint
extends: eslint-config-airbnb

env:
  es6: true
  node: true

rules:
  arrow-body-style:
    - error
    - as-needed
  no-param-reassign:
    - error
    - props: false

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
